import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const app = readFileSync(new URL("./App.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
const state = readFileSync(new URL("./state.ts", import.meta.url), "utf8");
const packageJson = readFileSync(new URL("../package.json", import.meta.url), "utf8");
const bridge = readFileSync(new URL("../bridge.py", import.meta.url), "utf8");
const bridgeEvents = readFileSync(new URL("../bridge_core/events.py", import.meta.url), "utf8");
const components = [
  "components/ChatSurface.tsx",
  "components/Composer.tsx",
  "components/ConversationRail.tsx",
  "tool_details.ts",
]
  .map((path) => readFileSync(new URL(path, import.meta.url), "utf8"))
  .join("\n");
const styles = readFileSync(new URL("./styles.css", import.meta.url), "utf8");
const source = `${app}\n${api}\n${state}\n${components}`;

test("webui uses HeroUI components for the agent workbench shell", () => {
  assert.match(source, /from "@heroui\/react"/);
  assert.match(source, /Chip/);
  assert.match(source, /Tooltip/);
  assert.match(source, /from "react-markdown"/);
  assert.match(source, /from "remark-gfm"/);
  assert.match(source, /新建聊天/);
  assert.match(source, /搜索/);
  assert.match(source, /最近/);
  assert.match(source, /暂无会话/);
  assert.match(source, /批量删除会话/);
  assert.match(source, /全选所有会话/);
  assert.match(source, /取消全选会话/);
  assert.match(source, /重新生成标题/);
  assert.match(source, /删除会话/);
  assert.match(source, /Ellipsis/);
  assert.match(source, /Loader2/);
  assert.match(source, /正在生成标题/);
  assert.match(source, /selectedIds\.length === sessions\.length/);
  assert.match(source, /删除 \{selectedIds\.length\} 个/);
  assert.match(source, /正在处理/);
  assert.match(source, /本轮执行完成/);
  assert.match(source, /tool\.start/);
  assert.match(source, /tool\.end/);
  assert.match(source, /timeline\.step/);
  assert.match(source, /artifact\.created/);
  assert.match(source, /ExecutionStep/);
  assert.match(source, /tool_name/);
  assert.match(source, /tool_label/);
  assert.match(source, /input/);
  assert.match(source, /output/);
  assert.match(source, /error/);
  assert.match(source, /default_open/);
  assert.match(source, /elapsed_ms/);
  assert.match(source, /timeline-step-duration/);
  assert.match(source, /\/session\/new/);
  assert.match(source, /answer\.delta/);
  assert.match(source, /answer\.final/);
  assert.match(source, /responses/);
  assert.match(source, /HeroBridge/);
  assert.match(source, /已连接/);
  assert.match(source, /Bridge 诊断/);
  assert.match(source, /Info/);
  assert.match(app, /bridgeDiagnosticsPanelRef/);
  assert.match(app, /bridgeDiagnosticsButtonRef/);
  assert.match(app, /pointerdown/);
  assert.match(app, /closeBridgeDiagnostics/);
  assert.doesNotMatch(source, /Settings2/);
  assert.match(source, /打开 mykey/);
  assert.match(source, /GA 根目录/);
  assert.match(source, /Bridge 配置/);
  assert.match(source, /BridgeConfigDetails/);
  assert.match(source, /配置项详情/);
  assert.match(source, /生效模型/);
  assert.match(source, /配置来源/);
  assert.match(source, /mykey\.py/);
  assert.match(source, /HTTP 接口/);
  assert.match(source, /事件通道/);
  assert.match(source, /可用 Profile/);
  assert.doesNotMatch(source, /WebSocket 事件/);
  assert.doesNotMatch(source, /Profile 数量/);
  assert.doesNotMatch(source, /原始 config/);
  assert.doesNotMatch(source, /会话数量/);
  assert.doesNotMatch(source, /mykeyPath \?\? "未连接"/);
  assert.doesNotMatch(source, /暂无配置项/);
  assert.match(api, /getBridgeConfig/);
  assert.match(api, /\/config/);
  assert.match(source, /openBridgePath/);
  assert.match(api, /regenerateSessionTitle/);
  assert.match(source, /modelProfiles/);
  assert.match(source, /selectedProfileId/);
  assert.match(source, /handleSwitchModelProfile/);
  assert.match(source, /切换生效模型/);
  assert.doesNotMatch(source, /<code title=\{activeProfileName\}>\{activeProfileName\}<\/code>/);
  assert.match(api, /switchModelProfile/);
  assert.match(api, /\/model-profile/);
  assert.match(styles, /white-space: nowrap/);
  assert.doesNotMatch(source, /<Label>切换生效模型<\/Label>/);
  assert.doesNotMatch(source, /当前模型配置/);
  assert.doesNotMatch(source, /模型\/Profile 面板/);
  assert.doesNotMatch(source, /model-profile-panel/);
  assert.match(source, /新会话/);
  assert.match(source, /deleteSessions/);
  assert.match(api, /cancelSession/);
  assert.match(api, /openBridgePath/);
  assert.match(api, /\/path\/open/);
  assert.match(api, /\/cancel/);
  assert.match(api, /\/model-profiles/);
  assert.match(api, /model\?: string/);
  assert.match(api, /\/status/);
  assert.match(api, /mapOutputsToTimeline/);
  assert.match(api, /mapEventsToTimeline/);
  assert.match(api, /emitBridgeOutputs/);
  assert.match(api, /parseGenericAgentOutputSteps/);
  assert.match(api, /after_event=/);
  assert.match(api, /payload\.events/);
  assert.match(api, /return steps\.length > 0 \? steps : mapOutputsToTimeline\(messages\)/);
  assert.match(api, /detail_delta/);
  assert.doesNotMatch(api, /isFinalResponseOutput/);
  assert.doesNotMatch(api, /filter\(\(output\) => !isFinalResponseOutput\(output\)\)/);
  assert.doesNotMatch(api, /Final response to user/);
  assert.match(api, /type: "timeline\.step"/);
  assert.doesNotMatch(api, /GenericAgent\.outputs/);
  assert.match(api, /images/);
  assert.match(source, /selectedImages/);
  assert.match(source, /image\/\*/);
  assert.match(source, /停止生成/);
  assert.match(source, /导出回答/);
  assert.match(source, /重新生成回答/);
  assert.match(source, /导出回答/);
  assert.match(source, /复制为 Markdown/);
  assert.match(source, /导出为 Markdown 文件/);
  assert.match(source, /useNowTick/);
  assert.match(source, /activeTurn\.startedAt/);
  assert.match(source, /Date\.parse\(activeTurn\.startedAt\)/);
  assert.match(source, /Math\.max\(nowTick - Date\.parse\(activeTurn\.startedAt\), 0\)/);
  assert.match(source, /turn-phase-duration/);
  assert.match(source, /已用时/);
  assert.match(source, /HistoryTimelineSummary/);
  assert.match(source, /timelineMode="summary"/);
  assert.match(source, /timelineMode="full"/);
  assert.match(source, /次工具调用/);
  assert.doesNotMatch(source, /turn-phase--footer[\s\S]*thinking-dots/);
  assert.match(source, /Dropdown\.Popover className="assistant-actions-popover"/);
  assert.match(source, /navigator\.clipboard\.writeText/);
  assert.match(source, /downloadMarkdownFile/);
  assert.match(app, /handleReplayTurn/);
  assert.match(app, /replayTurn/);
  assert.match(app, /await replayTurn\(/);
  assert.match(source, /正在加载会话/);
  assert.match(source, /消息导航/);
  assert.match(source, /跳到上一条用户消息/);
  assert.match(source, /跳到下一条用户消息/);
  assert.match(source, /回到最新消息/);
  assert.match(source, /Tooltip\.Content/);
  assert.match(source, /Tooltip\.Arrow/);
  assert.match(source, /placement="left"/);
  assert.match(source, /currentTop \+ 80/);
  assert.match(source, /data-user-message-anchor/);
  assert.match(source, /scrollToUserMessage\("previous"\)/);
  assert.match(source, /scrollToUserMessage\("next"\)/);
  assert.match(source, /appendFinalAssistantMessage/);
  assert.match(app, /applyStreamEvent\(activeTurnStateRef\.current \?\? createInitialTurnState\(turnId, startedAt\), event\)/);
  assert.match(app, /setActiveTurn\(nextTurn\)/);
  assert.match(app, /regeneratingTitleSessionId === activeSessionId/);
  assert.doesNotMatch(app, /activeTurn\?\.status === "streaming" \? "正在流式输出" : "已就绪"/);
  assert.match(app, /getBridgeStatus/);
  assert.match(app, /listModelProfiles/);
  assert.match(app, /const existing = await listSessions\(\)/);
  assert.match(app, /void refreshBridgeMetadata\(\{ silent: true \}\)/);
  assert.match(components, /session-count-badge/);
  assert.match(components, /会话数/);
  assert.match(app, /artifacts=\{artifacts\}/);
  assert.match(app, /timeline=\{timeline\}/);
  assert.doesNotMatch(app, /timeline=\{activeTurn \? \[\] : timeline\}/);
  assert.doesNotMatch(app, /artifacts=\{activeTurn \? \[\] : artifacts\}/);
  assert.doesNotMatch(app, /Promise\.all\(\[\s*listSessions\(\),\s*getBridgeStatus\(\),\s*listModelProfiles\(\)\s*\]\)/s);
  assert.doesNotMatch(app, /bridgeStatus\?\.sessionCount \?\? sessions\.length/);
  assert.doesNotMatch(app, /activeTurn \? "正在流式输出" : "已就绪"/);
  assert.match(components, /scrollTo\(\{ top: scrollElement\.scrollHeight/);
  assert.doesNotMatch(source, /Library/);
  assert.doesNotMatch(source, /Explore/);
  assert.doesNotMatch(source, /New Chat/);
  assert.doesNotMatch(source, /New chat/);
  assert.doesNotMatch(source, /分享/);
  assert.doesNotMatch(source, /modelLabel="GPT-5\.4"/);
  assert.doesNotMatch(source, /晚餐快手菜建议/);
  assert.doesNotMatch(source, /Understanding request/);
  assert.doesNotMatch(source, /正在理解请求/);
  assert.doesNotMatch(source, /Working/);
  assert.doesNotMatch(source, /Unknown error/);
  assert.doesNotMatch(source, /回答有帮助/);
  assert.doesNotMatch(source, /回答没有帮助/);
  assert.doesNotMatch(source, /更多回答操作/);
  assert.doesNotMatch(source, /任务已完成，您可随时发起新请求。/);
  assert.doesNotMatch(source, /<span>回到最新消息<\/span>/);
  assert.doesNotMatch(state, /title:\s*"任务已完成"/);
  assert.doesNotMatch(source, /ThumbsUp/);
  assert.doesNotMatch(source, /ThumbsDown/);
  assert.doesNotMatch(app, /refreshMessagesAfterTurn/);
});

test("webui keeps the screenshot-style chat layout contract", () => {
  assert.match(styles, /\.chat-workbench-shell/);
  assert.match(styles, /\.chat-workbench-shell\.is-sidebar-collapsed/);
  assert.match(styles, /\.workspace-sidebar/);
  assert.match(styles, /\.conversation-header/);
  assert.match(styles, /\.conversation-scroll/);
  assert.match(styles, /\.message-row--user/);
  assert.match(styles, /\.composer-card/);
  assert.match(styles, /\.session-count-badge/);
  assert.match(styles, /\.recent-item-actions/);
  assert.match(styles, /\.recent-item-status/);
  assert.match(styles, /\.session-actions-popover/);
  assert.match(styles, /\.session-actions-item/);
  assert.match(styles, /\.assistant-actions-popover/);
  assert.match(styles, /\.assistant-action-item/);
  assert.match(styles, /\.recent-item/);
  assert.match(styles, /\.batch-delete-bar/);
  assert.match(styles, /width: 100%/);
  assert.match(styles, /transition: grid-template-columns 220ms/);
  assert.match(styles, /--sidebar-width: 240px/);
  assert.match(styles, /grid-template-columns: var\(--sidebar-width\) 8px minmax\(0, 1fr\)/);
  assert.match(styles, /\.sidebar-resize-handle/);
  assert.match(app, /SIDEBAR_WIDTH_STORAGE_KEY/);
  assert.match(app, /localStorage\.getItem\(SIDEBAR_WIDTH_STORAGE_KEY\)/);
  assert.match(app, /localStorage\.setItem\(SIDEBAR_WIDTH_STORAGE_KEY/);
  assert.match(app, /onPointerDown=\{handleSidebarResizePointerDown\}/);
  assert.match(styles, /grid-template-rows: 64px minmax\(0, 1fr\) auto/);
  assert.match(styles, /\.conversation-main\s*{[^}]*grid-column: 3/s);
  assert.match(styles, /\.conversation-main\s*{[^}]*height: 100vh/s);
  assert.match(styles, /\.conversation-scroll\s*{[^}]*overflow-y: auto/s);
  assert.match(styles, /\.conversation-scroll::\-webkit-scrollbar/);
  assert.match(styles, /scrollbar-width: thin/);
  assert.match(styles, /\.message-scroll-nav/);
  assert.match(styles, /\.message-scroll-nav-button/);
  assert.match(styles, /\.message-scroll-nav-latest/);
  assert.match(styles, /\.message-scroll-nav\s*{[^}]*position: absolute/s);
  assert.match(styles, /\.message-scroll-nav\s*{[^}]*flex-direction: column/s);
  assert.match(styles, /--conversation-content-width: 72%/);
  assert.match(styles, /\.conversation-thread\s*{[^}]*width: var\(--conversation-content-width\)/s);
  assert.match(styles, /\.composer-dock\s*{[^}]*width: var\(--conversation-content-width\)/s);
  assert.match(styles, /\.profile-switch\s*{[^}]*width: 100%/s);
  assert.match(styles, /\.conversation-thread\s*{[^}]*min-width: 0/s);
  assert.match(styles, /\.turn-round\s*{[^}]*min-width: 0/s);
  assert.match(styles, /\.execution-timeline\s*{[^}]*min-width: 0/s);
  assert.match(styles, /\.timeline-step-card\s*{[^}]*max-width: 100%/s);
  assert.doesNotMatch(styles, /714px/);
  assert.doesNotMatch(styles, /\.profile-switch\s*{[^}]*min-width: 16rem/s);
  assert.doesNotMatch(styles, /\.profile-switch\s*{[^}]*width: 34%/s);
  assert.match(styles, /\.historical-timeline-summary/);
  assert.match(styles, /\.historical-timeline-summary-trigger/);
  assert.match(styles, /\.composer-input\s*{[^}]*min-height: 72px/s);
  assert.match(styles, /\.composer-actions-row/);
  assert.match(styles, /\.composer-model-switch/);
  assert.match(styles, /\.composer-model-popover/);
  assert.match(styles, /\.composer-model-option/);
  assert.match(styles, /\.message-bubble\s*{[^}]*font-size: 16px/s);
  assert.match(styles, /\.message-bubble :where\(pre\)/);
  assert.match(styles, /\.conversation-loading/);
  assert.match(styles, /\.turn-timeline/);
  assert.match(styles, /\.thinking-dots/);
  assert.match(styles, /@keyframes thinking-dot-bounce/);
  assert.match(styles, /\.timeline-step-card/);
  assert.match(styles, /\.thought-panel/);
  assert.match(styles, /\.artifact-card/);
  assert.match(styles, /\.tool-card/);
  assert.match(styles, /\.timeline-step-trigger-main/);
  assert.match(styles, /\.timeline-step-trigger-meta/);
  assert.match(styles, /\.timeline-step-trigger\s*{[^}]*white-space: normal/s);
  assert.match(styles, /\.timeline-step-trigger\s*{[^}]*align-items: center/s);
  assert.doesNotMatch(styles, /\.timeline-step-trigger\s*{[^}]*align-items: flex-start/s);
  assert.match(styles, /\.timeline-step-title\s*{[^}]*word-break: break-word/s);
  assert.match(components, /buildToolDetailSections/);
  assert.match(components, /默认：扫描当前浏览器标签页/);
  assert.match(components, /默认：执行本轮回复中的代码块/);
  assert.match(components, /默认：执行本轮回复中的 JavaScript 代码块/);
  assert.match(components, /isEmptyJsonObject/);
  assert.match(components, /readStepHeadline/);
  assert.match(components, /readToolNameIcon/);
  assert.match(components, /normalizeToolName/);
  assert.match(components, /MessageCircleQuestion/);
  assert.match(components, /MessageSquareText/);
  assert.match(components, /FileSearch/);
  assert.match(components, /FilePenLine/);
  assert.match(components, /Globe/);
  assert.match(components, /MousePointerClick/);
  assert.match(components, /Code2/);
  assert.match(components, /if \(toolNameIcon\) \{/);
  assert.match(components, /includes\("ask_user"\)/);
  assert.match(components, /includes\("file_read"\)/);
  assert.match(components, /includes\("file_write"\)/);
  assert.match(components, /includes\("web_scan"\)/);
  assert.match(components, /step\.kind === "phase"/);
  assert.match(components, /<MessageSquareText size=\{14\} \/>/);
  assert.match(components, /!isModelSummaryStep\(step\)/);
  assert.doesNotMatch(components, /AskUserChoices/);
  assert.doesNotMatch(components, /onAskUserChoice/);
  assert.match(app, /HumanInteractionPromptPanel/);
  assert.match(app, /humanInteractionPrompt=\{humanInteractionPrompt\}/);
  assert.match(app, /HumanInteractionPromptCard/);
  assert.match(app, /useIsPresent/);
  assert.match(app, /aria-label="ask_user 待选回复"/);
  assert.match(app, /ask-user-choice-list/);
  assert.match(app, /onAskUserChoice=\{\(choice\) => void handleSubmit\(choice\)\}/);
  assert.match(components, /label: "入参"/);
  assert.match(components, /label: "结果"/);
  assert.match(components, /label: sections\.length > 0 \? "过程" : "详情"/);
  assert.doesNotMatch(components, /readSummaryFromModelDetail/);
  assert.doesNotMatch(components, /timeline-tool-name/);
  assert.doesNotMatch(components, /timeline-tool-label/);
  assert.match(components, /className=\{`tool-detail-section tool-detail-section--\$\{section\.kind\}`\}/);
  assert.match(styles, /\.tool-detail-section\s*{[^}]*border: 1px solid #e0e1e7/s);
  assert.match(styles, /\.ask-user-panel\s*{/);
  assert.match(styles, /\.composer-ask-user-panel\s*{[^}]*width: var\(--conversation-content-width\)/s);
  assert.match(styles, /\.ask-user-choice-list\s*{[^}]*flex-wrap: wrap/s);
  assert.match(styles, /\.tool-detail-section pre\s*{[^}]*overflow-wrap: anywhere/s);
  assert.match(styles, /\.timeline-step-duration/);
  assert.match(styles, /\.timeline-step--tape/);
  assert.match(styles, /\.timeline-step--agent/);
  assert.match(styles, /\.timeline-step--tool/);
  assert.match(styles, /\.bridge-diagnostics-panel/);
  assert.doesNotMatch(styles, /\.bridge-diagnostics-panel--closing/);
  assert.doesNotMatch(styles, /animation: bridge-panel-in/);
  assert.doesNotMatch(styles, /animation: bridge-panel-out/);
  assert.match(styles, /\.bridge-config-details/);
  assert.match(styles, /\.bridge-config-grid/);
  assert.match(styles, /\.bridge-config-item/);
  assert.match(styles, /\.bridge-diagnostics-summary/);
  assert.match(styles, /\.bridge-diagnostics-actions\s*{[^}]*justify-content: flex-end/s);
  assert.match(styles, /\.bridge-diagnostics-panel > \.bridge-diagnostics-actions\s*{[^}]*display: flex/s);
  assert.doesNotMatch(styles, /\.model-profile-panel/);
  assert.doesNotMatch(styles, /@keyframes bridge-panel-in/);
  assert.doesNotMatch(styles, /@keyframes bridge-panel-out/);
  assert.match(styles, /\.composer-attachment-list/);
  assert.match(styles, /\.recent-item\s*{[^}]*font-size: 14px/s);
  assert.doesNotMatch(styles, /\.turn-complete/);
  assert.doesNotMatch(styles, /\.share-button/);
  assert.doesNotMatch(styles, /\.model-button/);
});

test("Composer exposes image attachments and a streaming cancel action", () => {
  const composer = readFileSync(new URL("components/Composer.tsx", import.meta.url), "utf8");

  assert.match(composer, /import type \{ ImageAttachment \} from "\.\.\/types"/);
  assert.match(composer, /onSubmit: \(content: string, images: ImageAttachment\[\]\) => void/);
  assert.match(composer, /modelProfiles: ModelProfile\[\]/);
  assert.match(composer, /selectedProfileId: string/);
  assert.match(composer, /onModelProfileSelect: \(profileId: string\) => void/);
  assert.match(composer, /onCancel: \(\) => void/);
  assert.match(composer, /accept="image\/\*"/);
  assert.match(composer, /readAsDataURL/);
  assert.match(composer, /停止生成/);
  assert.match(composer, /切换生效模型/);
  assert.match(composer, /composer-actions-row/);
  assert.match(composer, /composer-model-switch/);
  assert.match(composer, /Select\.Popover className="composer-model-popover"/);
  assert.match(composer, /selectedProfile \? formatProfileOption\(selectedProfile\) : "选择模型"/);
});

test("model switch stays inside the composer instead of duplicating a separate dock bar", () => {
  const diagnosticsStart = app.indexOf("showBridgeDiagnostics");
  const diagnosticsEnd = app.indexOf("</header>", diagnosticsStart);
  const diagnosticsSource = app.slice(diagnosticsStart, diagnosticsEnd);
  const composerDockSource = app.slice(app.indexOf("<ChatSurface", diagnosticsEnd), app.indexOf("</section>", diagnosticsEnd));

  assert.match(diagnosticsSource, /<BridgeConfigDetails/);
  assert.match(composerDockSource, /selectedProfileId=\{selectedProfileId\}/);
  assert.match(composerDockSource, /onModelProfileSelect=\{handleSwitchModelProfile\}/);
  assert.doesNotMatch(composerDockSource, /model-hot-reload-bar/);
  assert.doesNotMatch(diagnosticsSource, /<ModelProfilePanel/);
  assert.doesNotMatch(composerDockSource, /<ModelProfilePanel/);
});

test("deleting inactive sessions does not interrupt the active turn stream", () => {
  const deleteStart = app.indexOf("async function handleDeleteSessions");
  const deleteEnd = app.indexOf("const activeSession", deleteStart);
  const deleteSource = app.slice(deleteStart, deleteEnd);

  assert.ok(deleteSource.indexOf("const activeWasDeleted") < deleteSource.indexOf("closeActiveSource"));
  assert.match(deleteSource, /if \(activeWasDeleted\) \{[\s\S]*closeActiveSource\(activeSourceRef\.current\)/);
  assert.match(deleteSource, /setActiveTurn\(\(current\) => \(activeWasDeleted \? null : current\)\)/);
});

test("selecting the already active session does not reset the transcript into loading", () => {
  const selectStart = app.indexOf("function handleSelectSession");
  const selectEnd = app.indexOf("async function handleSubmit", selectStart);
  const selectSource = app.slice(selectStart, selectEnd);

  assert.match(selectSource, /if \(sessionId === activeSessionId\) \{/);
  assert.ok(selectSource.indexOf("if (sessionId === activeSessionId)") < selectSource.indexOf("setIsLoadingMessages(true)"));
  assert.ok(selectSource.indexOf("if (sessionId === activeSessionId)") < selectSource.indexOf("setMessages([])"));
});

test("empty session state does not show title regeneration status", () => {
  assert.match(app, /const isRegeneratingActiveTitle = Boolean\(\s*activeSession && activeSessionId && regeneratingTitleSessionId === activeSessionId,/);
  assert.match(app, /isRegeneratingActiveTitle \? \(/);
  assert.doesNotMatch(app, /\{regeneratingTitleSessionId === activeSessionId \? \(/);
});

test("active turn phase is not rendered as an assistant fallback message", () => {
  const activeTurnStart = components.indexOf("function ActiveTurnTimeline");
  const activeTurnEnd = components.indexOf("function TimelineView", activeTurnStart);
  const activeTurnSource = components.slice(activeTurnStart, activeTurnEnd);

  assert.match(activeTurnSource, /turn-phase--footer/);
  assert.doesNotMatch(activeTurnSource, /showFallbackBubble/);
  assert.doesNotMatch(activeTurnSource, /<MessageBubble content=\{activeTurn\.phase\?\.label/);
  assert.doesNotMatch(activeTurnSource, /<AssistantActions \/>/);
});

test("completed active turns move into history so tool timeline collapses immediately", () => {
  const finishStart = app.indexOf("function finishActiveTurn");
  const finishEnd = app.indexOf("async function refreshSessions", finishStart);
  const finishSource = app.slice(finishStart, finishEnd);

  assert.match(app, /messagesRef = useRef<MessageRecord\[\]>\(\[\]\)/);
  assert.match(app, /timelineRef = useRef<ExecutionStep\[\]>\(\[\]\)/);
  assert.match(app, /artifactsRef = useRef<ArtifactRecord\[\]>\(\[\]\)/);
  assert.match(finishSource, /mergeCompletedTurnIntoHistory\(messagesRef\.current, timelineRef\.current, artifactsRef\.current, completedTurn\)/);
  assert.match(finishSource, /messagesRef\.current = history\.messages/);
  assert.match(finishSource, /setMessages\(history\.messages\)/);
  assert.match(finishSource, /setTimeline\(history\.timeline\)/);
  assert.match(finishSource, /setArtifacts\(history\.artifacts\)/);
  assert.match(finishSource, /setActiveTurn\(null\)/);
  assert.match(finishSource, /activeTurnStateRef\.current = null/);
});

test("model process cards stay collapsed and final answers stay normal messages", () => {
  const bridgeEventSource = `${bridge}\n${bridgeEvents}`;

  assert.match(bridgeEventSource, /event_type == "llm\.visible_delta"/);
  assert.match(bridgeEventSource, /"type": "answer\.delta"/);
  assert.match(bridgeEventSource, /"type": "answer\.retract"/);
  assert.match(bridgeEventSource, /"type": "answer\.final"/);
  assert.match(bridgeEventSource, /default_open/);
  assert.match(bridgeEventSource, /thinking_summary/);
  assert.doesNotMatch(bridgeEventSource, /模型输出：/);
  assert.doesNotMatch(bridgeEventSource, /摘要：/);
  assert.match(components, /isModelSummaryStep/);
  assert.match(components, /Boolean\(step\.default_open && !isModelSummaryStep\(step\)\)/);
  assert.match(components, /readStepHeadline/);
  assert.match(state, /case "answer\.retract"/);
  assert.doesNotMatch(components, /<thinking>/);
  assert.doesNotMatch(components, /<tool_use>/);
  assert.doesNotMatch(components, /file_content/);
});

test("Motion handles only block-level chat layout and ask_user panel transitions", () => {
  const chatSurface = readFileSync(new URL("components/ChatSurface.tsx", import.meta.url), "utf8");

  assert.match(packageJson, /"motion":/);
  assert.match(app, /import \{ AnimatePresence, motion, useIsPresent \} from "motion\/react"/);
  assert.match(chatSurface, /import \{ LayoutGroup, motion \} from "motion\/react"/);
  assert.match(chatSurface, /<LayoutGroup id="conversation-thread-layout">/);
  assert.match(chatSurface, /message\.role === "user" \? \(/);
  assert.match(chatSurface, /<motion\.article/);
  assert.match(chatSurface, /<\/motion\.article>/);
  assert.match(chatSurface, /: \(\s*<article/s);
  assert.match(chatSurface, /<\/article>\s*\)/s);
  assert.match(chatSurface, /<motion\.section/);
  assert.match(chatSurface, /<motion\.div/);
  assert.match(chatSurface, /layout="position"/);
  assert.match(chatSurface, /layout="preserve-aspect"/);
  assert.match(chatSurface, /initial=\{\{ opacity: 0, scale: 0\.985, y: 16 \}\}/);
  assert.doesNotMatch(chatSurface, /message\.role === "user" \? 0\.985 : 0\.995/);
  assert.doesNotMatch(chatSurface, /message\.role === "user" \? 16 : 10/);
  assert.match(chatSurface, /whileHover=\{\{ scale: 1\.008, x: 2 \}\}/);
  assert.match(app, /<AnimatePresence initial=\{false\}>/);
  assert.match(app, /<motion\.div/);
  assert.match(app, /className="bridge-diagnostics-panel"/);
  assert.match(app, /initial=\{\{ opacity: 0, scale: 0\.96, y: -12 \}\}/);
  assert.match(app, /exit=\{\{ opacity: 0, scale: 0\.96, y: -10 \}\}/);
  assert.match(app, /key=\{activePrompt\.stepId\}/);
  assert.match(app, /initial=\{\{ opacity: 0, scale: 0\.96, y: 18 \}\}/);
  assert.match(app, /exit=\{\{ opacity: 0, scale: 0\.96, y: 14 \}\}/);
  assert.match(app, /transition=\{\{ damping: 22, mass: 0\.8, stiffness: 260, type: "spring" \}\}/);
  assert.doesNotMatch(app, /PROMPT_PANEL_ANIMATION_MS/);
  assert.doesNotMatch(app, /animationTimerRef/);
  assert.doesNotMatch(app, /animationFrameRef/);
  assert.doesNotMatch(app, /requestAnimationFrame/);
  assert.doesNotMatch(app, /ask-user-panel--enter/);
  assert.doesNotMatch(app, /ask-user-panel--exit/);
  assert.doesNotMatch(styles, /@keyframes message-in/);
});
