import type { ThemeConfig } from "antd";

export const gaPalette = {
  bg: "#f7f7f5",
  canvas: "#ffffff",
  shell: "#ffffff",
  shellMuted: "#f3f3f1",
  sidebar: "#f3f3f1",
  sidebarActive: "#ffffff",
  panel: "#ffffff",
  surface: "#f6f6f3",
  surfaceStrong: "#eeeeea",
  elevated: "#ffffff",
  line: "#e3e1dc",
  lineStrong: "#c9c5bd",
  text: "#242424",
  textStrong: "#111111",
  muted: "#6f6f6b",
  mutedSoft: "#9a9892",
  primary: "#0f766e",
  primaryHover: "#0b5f59",
  primarySoft: "#e6f4ef",
  primarySubtle: "#f1f8f5",
  info: "#256f8a",
  success: "#16845b",
  danger: "#b42318",
  warning: "#a15c07",
  codeBg: "#111827",
  codeText: "#eef2ff",
  userBubble: "#ffffff",
};

export const gaTheme: ThemeConfig = {
  token: {
    colorPrimary: gaPalette.primary,
    colorSuccess: gaPalette.success,
    colorError: gaPalette.danger,
    colorWarning: gaPalette.warning,
    colorInfo: gaPalette.info,
    colorBgBase: gaPalette.bg,
    colorBgLayout: gaPalette.bg,
    colorBgContainer: gaPalette.panel,
    colorBgElevated: gaPalette.elevated,
    colorBorder: gaPalette.line,
    colorBorderSecondary: gaPalette.line,
    colorText: gaPalette.text,
    colorTextHeading: gaPalette.textStrong,
    colorTextSecondary: gaPalette.muted,
    colorTextTertiary: gaPalette.mutedSoft,
    colorFillSecondary: gaPalette.surface,
    colorFillTertiary: gaPalette.shellMuted,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    controlHeight: 38,
    controlHeightLG: 42,
    controlHeightSM: 32,
    fontFamily:
      '"Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 14,
    lineHeight: 1.55,
    boxShadow: "0 0.625rem 2.125rem rgba(15, 23, 42, 0.08)",
    boxShadowSecondary: "0 0.0625rem 0.125rem rgba(15, 23, 42, 0.05)",
    motionDurationFast: "0.14s",
    motionDurationMid: "0.2s",
    motionDurationSlow: "0.28s",
  },
  components: {
    Button: {
      borderRadius: 6,
      controlHeight: 38,
      fontWeight: 600,
      defaultShadow: "none",
      primaryShadow: "none",
      textHoverBg: "rgba(17, 17, 17, 0.04)",
    },
    Select: {
      borderRadius: 6,
      selectorBg: "#ffffff",
      optionSelectedBg: gaPalette.primarySoft,
      optionActiveBg: gaPalette.surface,
      activeBorderColor: gaPalette.primary,
      hoverBorderColor: gaPalette.lineStrong,
    },
    Input: {
      borderRadius: 6,
      activeBorderColor: gaPalette.primary,
      hoverBorderColor: gaPalette.lineStrong,
      activeShadow: "0 0 0 0.1875rem rgba(15, 118, 110, 0.12)",
    },
    Dropdown: {
      paddingBlock: 6,
      zIndexPopup: 1200,
    },
    Modal: {
      borderRadiusLG: 8,
      contentBg: "#ffffff",
      headerBg: "#ffffff",
      footerBg: "#ffffff",
      titleColor: gaPalette.textStrong,
      titleFontSize: 17,
    },
    Drawer: {
      zIndexPopup: 1200,
    },
    Tag: {
      borderRadiusSM: 4,
    },
    Segmented: {
      itemSelectedBg: "#ffffff",
      itemSelectedColor: gaPalette.textStrong,
      trackBg: gaPalette.surface,
    },
    Card: {
      borderRadiusLG: 8,
      headerBg: "#ffffff",
    },
  },
};
