import type { ThemeConfig } from "antd";

export const gaPalette = {
  bg: "#f4f6f8",
  canvas: "#f8fafb",
  shell: "#161a22",
  shellMuted: "#252b35",
  sidebar: "#edf1f5",
  sidebarActive: "#ffffff",
  panel: "#ffffff",
  surface: "#f7f9fb",
  surfaceStrong: "#eef3f6",
  elevated: "#ffffff",
  line: "#d9e0e8",
  lineStrong: "#b8c3cf",
  text: "#1d2430",
  textStrong: "#111827",
  muted: "#5b6678",
  mutedSoft: "#8a95a5",
  primary: "#0f766e",
  primaryHover: "#0b5f59",
  primarySoft: "#e7f5f2",
  primarySubtle: "#f0faf8",
  info: "#0e7490",
  success: "#16845b",
  danger: "#c2413d",
  warning: "#b26a18",
  codeBg: "#111827",
  codeText: "#eef2ff",
  userBubble: "#172033",
};

export const gaTheme: ThemeConfig = {
  token: {
    colorPrimary: gaPalette.primary,
    colorSuccess: gaPalette.success,
    colorError: gaPalette.danger,
    colorWarning: gaPalette.warning,
    colorInfo: gaPalette.info,
    colorBgBase: gaPalette.bg,
    colorBgLayout: gaPalette.bg,
    colorBgContainer: gaPalette.panel,
    colorBgElevated: gaPalette.elevated,
    colorBorder: gaPalette.line,
    colorBorderSecondary: "#e7ecf2",
    colorText: gaPalette.text,
    colorTextHeading: gaPalette.textStrong,
    colorTextSecondary: gaPalette.muted,
    colorTextTertiary: gaPalette.mutedSoft,
    colorFillSecondary: "#eef2f6",
    colorFillTertiary: "#f4f7fa",
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    controlHeight: 38,
    controlHeightLG: 44,
    controlHeightSM: 32,
    fontFamily:
      '"Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    fontSize: 14,
    lineHeight: 1.55,
    boxShadow: "0 16px 36px rgba(17, 24, 39, 0.12)",
    boxShadowSecondary: "0 8px 22px rgba(17, 24, 39, 0.08)",
    motionDurationFast: "0.14s",
    motionDurationMid: "0.2s",
    motionDurationSlow: "0.28s",
  },
  components: {
    Button: {
      borderRadius: 8,
      controlHeight: 38,
      fontWeight: 600,
      defaultShadow: "none",
      primaryShadow: "none",
      textHoverBg: "rgba(15, 118, 110, 0.08)",
    },
    Select: {
      borderRadius: 8,
      selectorBg: "#ffffff",
      optionSelectedBg: gaPalette.primarySoft,
      optionActiveBg: "#f2f6f7",
      activeBorderColor: gaPalette.primary,
      hoverBorderColor: "#8fa0ad",
    },
    Input: {
      borderRadius: 10,
      activeBorderColor: gaPalette.primary,
      hoverBorderColor: "#8fa0ad",
      activeShadow: "0 0 0 3px rgba(15, 118, 110, 0.14)",
    },
    Dropdown: {
      paddingBlock: 6,
      zIndexPopup: 1200,
    },
    Modal: {
      borderRadiusLG: 12,
      contentBg: "#ffffff",
      headerBg: "#ffffff",
      footerBg: "#ffffff",
      titleColor: gaPalette.textStrong,
      titleFontSize: 17,
    },
    Drawer: {
      zIndexPopup: 1200,
    },
    Tag: {
      borderRadiusSM: 999,
    },
  },
};
